site_name: boxDocs
site_url: https://boxcutter-manual.readthedocs.io/
theme: readthedocs

pages:
  - About BoxCutter: index.md
  - Sales Page: boxcutter_page.html

  - Getting Started w/ Boxcutter:
    - Installation: install.md
    - Preferences: preference.md
    - Getting Started: getstarted.md
    - Troubleshooting: troubleshooting.md
    - Interface: interface.md
    - Fade: fade.md
    - Shapes: shapes.md
    - Hotkeys: hotkeys.md
    - Dots: dots.md

  - Questions And Answers:
    - FAQ: faq.md

  - Shapes (In Depth):
    - Box: shape_box.md
    - Circle: shape_circle.md
    - NGon: shape_ngon.md
    - Custom: shape_custom.md

  - Modes (In Depth):
    - Cut: mode_red.md
    - Slice: mode_yellow.md
    - Inset: mode_purple.md
    - Join: mode_green.md
    - Knife: mode_blue.md
    - Extract: mode_black.md
    - Make: mode_grey.md

  - Tool and Systems:
    - Edit Mode: edit_mode.md
    - Modal: modal.md
    - Widgets: widgets.md
    - Menus: menus.md
    - Modes: modes.md
    - Operations: operations.md
    - Snapping: snapping.md
    - Alignment: alignment.md

  - Tips & Tricks: tips.md
  - Zbrush: zbrush.md

  - Releases:
    - 714: 714.html
    - 713: 713.html
    - 712: 712.html
    - 711: 711.html

markdown_extensions:
    - admonition
    - footnotes
theme: readthedocs
extra_css:
    - css/extra.css
