site_name: Boxcutter Documentation
site_url: https://boxcutter-manual.readthedocs.io/
theme: readthedocs

pages:
  - BoxCutter: index.md
  - Getting Started:
    - Installation: install.md
    - Getting Started: getstarted.md
    - Interface: interface.md
    - Hotkeys: hotkeys.md
    - Preferences: preference.md
    - FAQ: faq.md

  - Modes:
    - Cut: mode_red.md
    - Slice: mode_yellow.md
    - Inset: mode_purple.md
    - Join: mode_green.md
    - Knife: mode_blue.md
    - Extract: mode_black.md
    - Make: mode_grey.md

  - Shapes:
    - Box: shape_box.md
    - Circle: shape_circle.md
    - NGon: shape_ngon.md
    - Custom: shape_custom.md

  - Tool:
    - Modal: modal.md
    - Modes: modes.md
    - Shapes: shapes.md
    - Operations: operations.md
    - Alignment: alignment.md
    - Snapping: snapping.md
    - Menus: menus.md
    - Settings: settings.md

  - Tips & Tricks: tips.md

markdown_extensions:
    - admonition
    - footnotes
theme: readthedocs
extra_css:
    - css/extra.css
